[package]
name = "simple-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env-loader = { git = "https://github.com/jm-alan/env-loader" }
regex = "1.7.1"
